### ISSUE TITLE
Update wiki page - devices all work

### ISSUE THREAD

**Issue by shanelilley** [bwp91/homebridge-ewelink#145]
hi @bwp91 
I have just installed Sonoff/ewelink Zigbee bridge with each of the listed sub devices and I can confirm they all work perfectly in your plugin and Homebridge/Homekit. 

I think the wiki should be updated to say they definitely work perhaps?

Great work! :) 

The plugin should work with the Sonoff Zigbee Bridge with the subdevices listed below.

Supported:
Zigbee Single Switch
Zigbee SNZB-01 Button
Zigbee SNZB-02 Temp/Humidity Sensor
Zigbee SNZB-03 Motion Sensor
Zigbee SNZB-04 Door/Window Sensor

Kind regards,
Shane

**Comment by bwp91** [comment]
Blimey, some good news on here for a change!

I'm really glad it's all working well for you.

My choice of the word "should" on the wiki is intentional, for all devices (even the ones I own that I know absolutely definitely work). As errors do crop up from time to time!

Thanks a lot for your feedback :)
