### ISSUE TITLE
What about renaming the devices?

### ISSUE THREAD

**Issue by Jetro97** [bwp91/homebridge-ewelink#181]
* **Please explain your feature request in a one or two sentences.** 
Possibility to rename ewelink devices original name.

* **Is your feature request related to a problem? Please describe.**

Since the name set in ewelink is not displayed in homebridge (al least only on 2 out of 10 MINIR2), and the name set in homebridge is not shown in the logs it is difficult to understand what device has been triggered by the log.

* **Any particular eWeLink devices that this relates to?**

MINIR2 in my case, not tested on other devices

* **Anything else?**

Thank you so much

**Comment by bwp91** [comment]
Hi @Jetro97 
The accessory's name that is shown in the logs is the name of the accessory from when it was originally added to Homebridge. This name remains constant even if the name is changed via eWeLink app, Homebridge or the Home app.
The only way to change the 'log' name is to remove the accessory from Homebridge so that it is re-added again.
You'll need to:

1. Name the device in the eWeLink app how you wish for it to appear in Homebridge
2. Use config-ui-x to remove the accessory from the Homebridge cache
3. The accessory will automatically be re-added once Homebridge has restarted

Please bear in mind that this will reset the accessory, ie, remove it from it's set room in the HomeKit and also remove it from any associated automations.

Unfortunately this currently the only way to update the accessory name as shown in the logs.

Thanks

**Comment by Jetro97** [comment]
Hi @bwp91 

Thank you, i've already tried it but the devices are always shown with the original name (i've named it all during the first installation but only 2 of them are actually showing the name assigned).

All the names are written with the same syntax: "Rele 01", "Rele 02" ... "Rele 10" since the first pairing, but only "Rele 01" and "Rele 10" are actually shown with their name on Homebridge...

**Comment by bwp91** [comment]
Could we message on my discord to try sort this out?
https://discord.gg/cMGhNtZ3tW

**Comment by Jetro97** [comment]
@bwp91 
Just made some tests: with new devices the names are assigned as expected. Maybe something went wrong during my first installation: i've renamed also the existing ones and now they also have the right name.

Thank you for support!!
