### ISSUE TITLE
Latest update breaks my 4CHPROR2 (PSF-B04-GL)  Sonoff switch

### ISSUE THREAD

**Issue by SaKiEQ** [bwp91/homebridge-ewelink#212]
### What issue do you have? Please be as thorough and explicit as possible.
After latest update my 4CHPROR2 (PSF-B04-GL) posts in Homebridge and Homeapp, but the switch does not react or receive any commands. Rolling back to previous homebridge-ewelink v5.0.6 version resolves the issue. 
All other eWlink single channel devices behave like before. 
I tried adding it as multi-channel device manually in the config UI, same result. Removing it manually in the plugin-setup did not revert it back, removing the JSON config entry manually did not revert it back. Only reverting back the plugin to the v5.0.6. version resolves the issue. 

### Details of your setup.
* Homebridge on Raspberry Pi 4 +  config-ui, Node-Red. Node.js v14.15.5., NPM v6.14.11

* Which version of Homebridge/HOOBS do you have?
Latest v1.3.1

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?   -> see above 

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable. -> see above

### Please paste any relevant logs below.

In the log everything seems to be ok. Like all the single eWlink devices it seems to receive commands, but just ignores them. The Accessories UI in both Homebridge and Home.app reflect the state changes correctly, but the device it self does not react to it.

**Comment by bwp91** [comment]
Hi, thanks for bringing this to my attention.
Please try v5.1.1 which I have just published.
This should resolve this issue, let me know!

**Comment by SaKiEQ** [comment]
Thanks very much, solved it with a one click (update) solution !

**Comment by JakeMux** [comment]
Hi SaKiEQ, I have the same exact issue as above, but I’m on Hoobs, and there is no 5.1.1 available, only 5.1.0. Any idea when that version will come to Hoobs?
Thanks :)

**Comment by bwp91** [comment]
@JakeMux 
If the update hasn't appeared already, please do the following:

1. Stop HOOBS
2. Go to the terminal and run these commands separately:
    `cd ~/.hoobs/`
    `npm install homebridge-ewelink@latest`
3. Start HOOBS

Then eWeLink plugin should be updated to 5.1.1

**Comment by JakeMux** [comment]
Thanks Ben, that did the trick.
It was my 4CHPRO that wanted WAN connection instead of auto or LAN, even though it’s set to use LAN access in the ewelink app. It all worked fine up until yesterday, I updated Hoobs and your plugin to the latest, and then LAN access stopped working, and I had to set it to Wan for a workaround. The 5.1.1 version solves that, so good.

Now the next step is that my RPI Hoobs box drops communications on regular intervals. I just reinstalled the latest Hoobs RPI image from scratch this morning, installed your plugin, it worked for 30 minutes, now everything is “unavailable”, except the devices I have that are HomeKit certified - those work fine. No other plugins are installed. Reboots may or may not solve it, and when it does, my ewelink devices are working for 20-30 minutes, then go offline in the Home app. I can still control them from the Hoobs interface though.

I have the Hoobs box on both wifi and Ethernet, no problems with other devices on the same network, and my real HomeKit devices show up and works in the Home app fine.

Any ideas? I know it may not be you I need to talk to, but still... ;)

Jakob Muxoll
___________________
  


On 4 Mar 2021, at 09.23, Ben <notifications@github.com> wrote:

﻿
@JakeMux
If the update hasn't appeared already, please do the following:

Stop HOOBS
Go to the terminal and run these commands separately:
cd ~/.hoobs/
npm install homebridge-ewelink@latest
Start HOOBS
Then eWeLink plugin should be updated to 5.1.1

**Comment by bwp91** [comment]
Hi @JakeMux 

> It was my 4CHPRO that wanted WAN connection instead of auto or LAN

You're right, it was a problem with the lan connection I accidentally introduced when enabling lan functionality for the Sonoff D1.

> I can still control them from the Hoobs interface though.

The fact that you can still control the ewelink accessories from the HOOBS interface confirms that it is a connectivity problem between the HOOBS box and HomeKit apps.

Do you have a HomeKit bridge ie an apple tv, ipad or home hub always on?

**Comment by JakeMux** [comment]
Yeah, iPad that is always plugged in. Setup as Home hub. I have obviously added the whole family as users, but allowing myself and my wife to modify stuff from our own devices (different Apple ID’s, the iPad acting as hub has its own Apple ID). Thinking about it, after I reinstalled Hoobs this morning, I used my own iPhone to add the Hoobs hub to the system. It did show up fine on the iPad, but I’m thinking that I may have to delete it, then add Hoobs on the iPad directly instead.
At work now, but I’ll let you know if this works when I get home.

Thanks 🙏 

Jakob Muxoll
___________________
  


On 4 Mar 2021, at 10.50, Ben <notifications@github.com> wrote:

﻿
Hi @JakeMux

It was my 4CHPRO that wanted WAN connection instead of auto or LAN

You're right, it was a problem with the lan connection I accidentally introduced when enabling lan functionality for the Sonoff D1.

I can still control them from the Hoobs interface though.

The fact that you can still control the ewelink accessories from the HOOBS interface confirms that it is a connectivity problem between the HOOBS box and HomeKit apps.

Do you have a HomeKit bridge ie an apple tv, ipad or home hub always on?

**Comment by JakeMux** [comment]
Alright - I removed my Hoobs from the Home hub iPad, and re-added it. Seems stable now.

I think what happened was: The iPad has its own Apple ID, and runs as a Home hub in the house, always on (actually its wall mounted in a picture frame...). I had a “household” setup on it, and had added myself (different Apple ID than the iPad) as allowed to edit/add/delete stuff in the “household”, so I re-added my Hoobs box on my own phone, which then populated to the iPad. But it must have confused the iPad, and thus it lost comms to the Hoobs box sometimes. So I removed everything and started from scratch, on the iPad, and now everything seems stable.

Thanks so much for your help dude, you’re awesome :)

On 4 Mar 2021, at 10.50, Ben <notifications@github.com> wrote:

﻿
Hi @JakeMux

It was my 4CHPRO that wanted WAN connection instead of auto or LAN

You're right, it was a problem with the lan connection I accidentally introduced when enabling lan functionality for the Sonoff D1.

I can still control them from the Hoobs interface though.

The fact that you can still control the ewelink accessories from the HOOBS interface confirms that it is a connectivity problem between the HOOBS box and HomeKit apps.

Do you have a HomeKit bridge ie an apple tv, ipad or home hub always on?
