### ISSUE TITLE
Accessories lost

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-ewelink#236]
Ben, sometimes some homebridge plug-in after removed still in HK the accessorie tile.
The only way to clean up is to cancel the cache but this needs to a complete reconfiguration of your automations and scenes.
On terminal, with sudo rm -rf accessories it's possible to achieve the same goal without deleting the complete cache.
The only issue still with your plug-in (EWeLink, Govee and deboots)
All accessories from your plugins lost the name and type information (and for that is necessary to recreate automations and scene)
The other plug-in installed not losing the informations.
Do you have any idea why this happen?
Thanks
Stefano

**Comment by bwp91** [comment]
Hi @Stetocasa 

The command `sudo rm -rf accessories` is deleting the cache folder ie deleting the accessory cache.

So accessories will need to be re-added to Homebridge and naturally the associated names, rooms, scenes and automations will be lost.

Which plugin are you talking about that you say doesn't?

**Comment by Stetocasa** [comment]
- tuya web
- delay switch
- dummy switch
- Meross
- Samsung tizen 
- switchbot lock 
- toogle switch

Those plug-in doesn't losing informations after clear the folder. Again, just EWeLink,govee and Ecovacs

**Comment by bwp91** [comment]
I am not totally sure why this is happening with my plugins.

I understand sometimes the need to delete the accessories folder to sometimes remove redundant accessories from uninstalled plugins.

However in the upcoming version of HOOBS (4) this will no longer be required as there is the ability to remove specific accessories from the cache instead of a general wipeout. This will mean you won't ever need to delete the accessories folder again :)

**Comment by Stetocasa** [comment]
Fantastic news for Hoobs 4 features !
Thanks
