### ISSUE TITLE
Device update failed

### ISSUE THREAD

**Issue by ands0me** [bwp91/homebridge-ewelink#237]
### What issue do you have? Please be as thorough and explicit as possible.
-device update failed as websocket request was rejected by timeout.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
-1.

* Which version of Homebridge/HOOBS do you have?
-V.1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
-Raspberry Pi

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
-v6.1.2
-I think so

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
-LED Strip 

### Please paste any relevant logs below.

![4128BDC3-F41F-43D8-8CCF-2C3CC3F2B600](https://user-images.githubusercontent.com/74508966/114775449-9add6d00-9d71-11eb-9bab-e6aa9cf6df0a.jpeg)

**Comment by bwp91** [comment]
hi @ands0me 

do you use the same ewelink account for the app on your phone and for homebridge?

**Comment by ands0me** [comment]
> hi @ands0me
> 
> do you use the same ewelink account for the app on your phone and for homebridge?

Yes.

i checked the plug-in version. From version 6.0.1 it’s Happening.

**Comment by ands0me** [comment]
Maybe you should know the device does not support LAN Mode.

**Comment by bwp91** [comment]
The error you are receiving is due to the fact that the plugin isn't receiving a response from ewelink when you send an update to the device. This is why I asked if you used the same ewelink account for your phone and for the plugin.

The 'responses' from ewelink are far more reliable when any device has been linked to an account and this account is used for the plugin too (ie no sharing of devices at all).

Issue https://github.com/bwp91/homebridge-ewelink/issues/234 (same error) was resolved by the person using their main ewelink account.

But in your case if there is definitely no sharing going on then I will need to think of a workaround.

Do you get this error **every** time you try to control the device? Or just sometimes? And when you control the device, does the physical device update even if you receive this error?

**Comment by ands0me** [comment]
> The error you are receiving is due to the fact that the plugin isn't receiving a response from ewelink when you send an update to the device. This is why I asked if you used the same ewelink account for your phone and for the plugin.
> 
> The 'responses' from ewelink are far more reliable when any device has been linked to an account and this account is used for the plugin too (ie no sharing of devices at all).
> 
> Issue #234 (same error) was resolved by the person using their main ewelink account.
> 
> But in your case if there is definitely no sharing going on then I will need to think of a workaround.
> 
> Do you get this error **every** time you try to control the device? Or just sometimes? And when you control the device, does the physical device update even if you receive this error?

I checked again the if it’s the same acoount. My fault I had different account on my phone and the plugin. I changed now to the same account. 

I tried the v6.1.2 and now it’s working.
So you’re right it was my fault 🤦🏻‍♂️ 

thank you 🙏🏻
