### ISSUE TITLE
Device update failed

### ISSUE THREAD

**Issue by ddong3000** [bwp91/homebridge-ewelink#245]
I same account use
This problem happening after reboot my raspi
After the first problem, the second try being ok
My plugin ver 6.2.1
Check plz! thanks alot!
![제목 없음](https://user-images.githubusercontent.com/54649785/116019755-e05a3e00-a67f-11eb-9b46-a4c3e5cfc75f.png)

**Comment by bwp91** [comment]
Hi @ddong3000 

In the log entry immediately before the warning, you can see the device was reported as offline.

This is most likely why you received the warning about the 'timeout' as obviously a device cannot be controlled by the plugin when it is offline.

**Comment by ddong3000** [comment]
Thanks your answer.
What should i do?
Can i increase the timeout' time?

It's Works even offline when i secondary triying...

**Comment by bwp91** [comment]
The timeout is there to stop Homebridge complaining that the device update is taking too long.

In the new version of the plugin I will increase the timeout from 5 to 6 seconds (I can't increase any more).

But in most circumstances I think that this won't have much of an effect as chances are if a device hasn't responded after 5 seconds then an extra second won't do much.

To be honest, there isn't that much you can do except making sure your devices are online.

As mentioned above, the timeout is there for a reason, otherwise Homebridge will report an error saying it is taking too long, and a different error will show. So either way there will be an error.

**Comment by ddong3000** [comment]
> The timeout is there to stop Homebridge complaining that the device update is taking too long.
> 
> In the new version of the plugin I will increase the timeout from 5 to 6 seconds (I can't increase any more).
> 
> But in most circumstances I think that this won't have much of an effect as chances are if a device hasn't responded after 5 seconds then an extra second won't do much.
> 
> To be honest, there isn't that much you can do except making sure your devices are online.
> 
> As mentioned above, the timeout is there for a reason, otherwise Homebridge will report an error saying it is taking too long, and a different error will show. So either way there will be an error.

Thank for your reply!!
Have a good day👍🏻😎
