### ISSUE TITLE
Aqara door/ window sensor as a contact sensor in Homebridge 

### ISSUE THREAD

**Issue by BaskaraR** [bwp91/homebridge-ewelink#263]
* **Please explain your feature request in a one or two sentences.**
Would like to know whether would it be possible to make Aqara door/window sensor as a contact sensor for garage door sensor as an alternative rather than using a sonoff DW2 -WiFi sensor?

* **Is your feature request related to a problem? Please describe.**

Been using the sonoff DW2 WiFi sensor quite some time now and the reliability in terms of battery consumption is very bad which makes the sensor goes offline within a week of usage with new batteries..
Been testing with aqara door sensor now and it’s way much reliable. The only problem is I can’t make it to sync with my garage door state (open or close). 

* **Any particular eWeLink devices that this relates to?**
* DW2 WiFi 

* **Anything else?**

**Comment by bwp91** [comment]
Hi @BaskaraR 

Any homebridge plugin cannot read accessory status from other native-HomeKit accessories or accessories from other homebridge plugins.

For this reason it would be impossible for the ewelink plugin to obtain the status of the aquara sensor, so obviously couldn't update the garage door accessory.

The only potential way of doing this would be slightly more complicated... the idea being you would need some form of ewelink device sending an update to the plugin when the contact sensor changes state...

For example if you were to set up a sonoff mini or basic... and use something like ifttt to update the ON/OFF of the switch as the contact sensor changes...

* contact detected turns the switch OFF
* contact not detected turns the switch ON

Then with a couple of changes to the plugin you could use this sonoff switch instead of the DW2 sensor.
