### ISSUE TITLE
Show offline as off

### ISSUE THREAD

**Issue by salahaki** [bwp91/homebridge-ewelink#268]
### What issue do you have? Please be as thorough and explicit as possible.

Hi. When the Sonoff device on ewelink is offline does not reflect back on Homebridge in which the device is always showing on even if you click on it to switch it off. Any way to have it synced as switched off when the Sonoff device is offline. thanks

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

* Which version of Homebridge/HOOBS do you have?

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @salahaki 

The issue with this is that offline does not necessarily mean that the switch is off.

For example, I have sonoff wall switches that sometimes disconnect from the wifi network, but the channels are still ON and so the lights are still ON. I would not want these lights to show as "OFF" in homekit just because they are offline from the network.

I do see your point however - one of my wall switches is connected to a sonoff bulb - meaning when the wall switch is OFF, the bulb has no power and is offline. If I turn the wall switch OFF when the bulb is ON, of course the bulb is actually off but it is still shown in homekit as ON.

However, in this same situation, if the bulb has power and is ON, but goes offline, it doesn't turn off. So I wouldn't want it shown as OFF in homekit.

The plugin **cannot** determine whether a device has gone offline due to either

* the device not having power (in this case it would make sense to show as OFF in homekit)
* a random disconnect from the wifi (in this case the device may still actually be ON so it would not make sense to show as OFF in homekit)

So I really am unsure the best way to reflect an offline device

Edit:
It isn't actually possible to mark an accessory as "no response" in the Homebridge UI.

**Comment by bwp91** [comment]
Could I message you on discord?

https://discord.gg/cMGhNtZ3tW

**Comment by salahaki** [comment]
Many thanks for reverting back. I have 2 mini DIY small switches; one is connected to generator 1 and another to generator 2. When generator 1 is off I need to see the switch in offline mode but in fact it stays on and I can not even switch it off manually.



Regards,
Salahaki

**Comment by bwp91** [comment]
I can make the devices appear as "no response" in the home app, but not in the homebridge app.

Please install the beta version of the plugin, and use the homebridge UI to turn on the setting "Offline Devices" in the optional settings section.

This *should* mark any offline accessory as "no response" in the home app, just saying it again, that this status is not available in the homebridge ui

**Comment by salahaki** [comment]
Many thanks. I will try it out and revert back 



Regards,
Salah Kanaan

**Comment by salahaki** [comment]
Hi,
Could you please guide me on where to find the beta version?
Thanks
Sal

**Comment by bwp91** [comment]
https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version#homebridge-ui

**Comment by bwp91** [comment]
<img width="500" alt="Screenshot 2021-06-24 at 08 45 42" src="https://user-images.githubusercontent.com/43026681/123223234-a0b9a200-d4c8-11eb-8ea5-220717c5d2e2.png">

Once installed, you should see this new "Offline Accessories" option in the settings. turn this on and restart homebridge

**Comment by salahaki** [comment]
Many thanks for your swift response and support. I will check and revert back.
Thanks again.
