### ISSUE TITLE
Sonoff SNZB-04 sensor 

### ISSUE THREAD

**Issue by BaskaraR** [bwp91/homebridge-ewelink#270]
Hi there,

I've recently purchased a sonoff snzb-04 zigbee sensor for my garage door with 2 channel. However for some reason the sensor coupled to the garage door as a door state indicator(open/close) causes the garage door to stop functioning. I'm using the accessory stimulations to make this work but for some reason it doesn't. I tried to remove the zigbee sensor from the accessory stimulation column (for sensor) and the garage door will function as normal. Unable to open the doors using homekit but using ewe link app to open the door works fine!

Homebrigbe with Pi
Node.js Version  v14.17.0
 using plugin  v6.8.1-beta.43 

Thanks for your help!

**Comment by bwp91** [comment]
Hi,

When you have the sensor configured as the garage simulation sensor, does the garage accessory show the correct state of the door (ie open or closed)?

When you say it’s “not working”, are there any messages in the logs that could pinpoint why?

**Comment by BaskaraR** [comment]
Hi,

When you have the sensor configured as the garage simulation sensor, does the garage accessory show the correct state of the door (ie open or closed)?

===> Yes, the zigbee sensors shows the correct state. However the door doesn't open physically using home kit/ homebridge. Since I've turned on  activity notification on my ios devices, i'll get notification that the door is open. However its physically not open and the Door **opening** sign showns in home kit. ( Same goes to closing as well).
Using the ewe link app no issue in terms of the sensor state and the door actually opens. (Shown in home kit) 

When you say it’s “not working”, are there any messages in the logs that could pinpoint why?
==> i can't seem to find any messages in the logs for the sensor part

let me know if you require the logs

Thanks for your prompt respond.

**Comment by bwp91** [comment]
I may have found the problem.

Can you update to the beta version of the plugin, v6.8.1-beta.44, to see if this has fixed this?

Thanks

**Comment by BaskaraR** [comment]
Hi bwp91,
 It works now after updated v6.8.1-beta.44. You're the man!!! :))
 Just curious though, what was the issue with the previous plugin version?

Many thanks...
Cheers!!!

**Comment by bwp91** [comment]
I made a change to the plugin recently with the simulations to auto-determine whether the device is single or multi channel (one less thing to configure for the user!)

In the particular case of the garage, the check was being skipped due to the presence of the sensor and so when you tried to control the device through homekit, the plugin didn’t know whether it was single or multi channel, and so just wasn’t doing anything.

If interested, the fix can be seen here:

https://github.com/bwp91/homebridge-ewelink/commit/0d10ef13d1d3cdf8069fc0bc2a45e57f9c6da3ba#diff-cbb728fe90612c3aea36db9e2769fc85c8768a69b0dccc8809b5b057a3ea3c82

**Comment by BaskaraR** [comment]
i see... thanks again. I'll close the case for now..
