### ISSUE TITLE
Ability to split into temp and switch

### ISSUE THREAD

**Issue by jacklawry** [bwp91/homebridge-ewelink#285]
* **Please explain your feature request in a one or two sentences.**

The ability to split the device into an input (useful to control other stuff based on the temp) or if on/off. 

* **Is your feature request related to a problem? Please describe.**

I can't turn the switch off (or perform other actions based on the temp)

* **Any particular eWeLink devices that this relates to?**

Sonoff HT16

* **Anything else?**

**Comment by bwp91** [comment]
Hi @jacklawry 

I don't believe it is possible to create HomeKit automations in the Home app based on temperature(/humidity).

This can be done via the Eve HomeKit app (not sure if you use this already) but it allows you to create more complex automations, based on temperature, based on the different services of an accessory (ie controlling the switch of a temperature sensor + switch combination accessory).

Is this what you're looking to do?

**Comment by jacklawry** [comment]
Thanks for your reply, I had tried to use Eve previously but the guides I found were quite old and didn't really apply to the current app. However, just tried again myself and I think I have got it working.

**Comment by bwp91** [comment]
If your automations are based on a single temperature point you can use the settings to expose the device in homekit as a heater or cooler.

eg if you want to turn ON if it drops below a certain temperature or OFF otherwise, you can expose as a heater.

if you want to turn OFF when it drops below a certain temperature or ON otherwise, you can use cooler.

in these cases then you don’t need the automations as the plugin will do the work.
