### ISSUE TITLE
Inching Board Status

### ISSUE THREAD

**Issue by fratinize** [bwp91/homebridge-ewelink#318]
So This Plug in Has worked great for my 4 Channel inching board (about a year ago. I have stopped using since) I plan to Reuse for another Purpose and Hope you can Direct me to something I missed in your docs, or a solution. nevertheless, I am Installing a Pool VS Pump That allows for 4 "control signals" Much Like the inching board. I select the Button, it sends the Signal, the pump Changes its speed. Great. How/Is there a way we can know what button the Pump is on? or at least know what button was last pressed? I am Probably missing alot, thank you for anyone that can decipher my objective.

**Comment by bwp91** [comment]
Hi @fratinize 

If you create an entry in the config section "Multi-Channel Devices" with a label, device ID, model, "show as" and "status by inching" set to `1,2,3,4` as below in the screenshot, the plugin will show the separate channels in the home app as ON/OFF based on inching rather than their actual state. I believe this is what your aim is?

![IMG_5650](https://user-images.githubusercontent.com/43026681/145358891-f990fba8-5712-4ee0-b05a-6bbf86a46364.jpeg)

When you turn a switch ON, the plugin will continue to show the home app accessory as ON even though the real state has turned back OFF due to the inching. If you turn OFF through the home app, the plugin will send an ON command which will then be turned OFF again due to the inching. 

This feature hasn't been extensively tested yet, but I think it's the kinda thing that you're looking for.

**Comment by fratinize** [comment]
Ty I will def try this out today

**Comment by bwp91** [comment]
cool let me know if it’s what suits your setup!

**Comment by fratinize** [comment]
I must apologize, I thought I had Replied to This as it Works Like a Charm. Or Should I say Worked. as Of 3 Days ago, I had to Replace my Power Panel to my Pool Equipment, My Power was off there for 2 Days, when I powered up, my inching board no longer communicated with my Pump. Odd. I can Hear the Board Click when I choose a Channel, but No change from the Pump. Also it seems my Board no longer looks like it did. There use to be 5 tiles. Speed 1, 2, 3 ,4 and one that Just said Variable Speed (I believe it is 0), nevertheless, The Variable Speed Tile is No Longer there. I am 100% confused. Almost seemed a cable went bad, but after seeing what the tiles look like (home bridge and HomeKit match) I am not so Sure. Any thoughts? I have Removed and Re added, but Still only the 4 tiles.
Thanx

**Comment by fratinize** [comment]
Tested the Cable and Pump and There seems to be zero issues with the Cable, I can Send the 5volts just fine from the cable and the pump behaves as expected. So Why All of a Sudden did the Board Stop sending the 5volts? Thinking I should try a New board, but there does not seem to be any obvious issue with it. It Responds to the ewe link app, but it, as mentioned above, it looks different. was that Something on the Program End? bwp91 ? Did that Programming Change Show after my Board was off line for a couple of days? Did something fail in the board? anybody and ideas? thoughts? ty

**Comment by fratinize** [comment]
Love to run this by you. First, This plug in has been awesome. So there have been many updates to everything involved. According to this question I posed and your answer I should have something in my config. I know I added at the time, but as I look at it, I do not anymore, yet it works perfectly. Did you make an update and I missed it (very real possibly)
Reason I ask is the board I have is acting funky so I want to try a new board and remember there was a setup to show the button I pressed that it was in fact on.
Hope this made sense
Ty
