### ISSUE TITLE
Sonoff 4Ch 

### ISSUE THREAD

**Issue by wumpsven** [bwp91/homebridge-ewelink#329]
Hej Friend, i have a Question.

Ich habe einen 4ChPro. 
Kanal 1 "Auf" und Kanal 2 "Zu" sind am Garagentor angeschlossen.
Kanal 3 "Auf" und Kanal 4 "Zu" steuern meine Wohnzimmer Rolläden.

Wie kann ich Kanal 1 und Kanal 2 als Garagentor, Kanal 3 und Kanal 4 als Fenster anzeigen lassen?
Ist es möglich Garagentor in Homekit Raum Garage, und Rolläden in Raum Wohnzimmer anzeigen zu lassen?

Bei der Auswahl 4 Garage Doors, sind alle 4 Kanäle im selben Raum.

Google Translater

I have a 4ChPro.
Channel 1 "open" and channel 2 "closed" are connected to the garage door.
Channel 3 "open" and channel 4 "closed" control my living room shutters.

How can I display channel 1 and channel 2 as a garage door, channel 3 and channel 4 as a window?
Is it possible to display the garage door in the Homekit room Garage and shutters in the living room room?

If you choose 4 Garage Doors, all 4 channels are in the same room.

**Comment by bwp91** [comment]
Hi @wumpsven 

For the moment you should be able to use the "2 Garage Doors" Show As option, as this uses channel 0 for opening door 1, channel 1 for closing door 1, channel 2 for opening door 2 and channel 3 for closing door 2.

However this will display as two garage doors, rather than a garage door and a window. And the option to show them in different rooms is unavailable.

**Comment by wumpsven** [comment]
Thanks for the answer
