### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MoTechnicalities** [bwp91/homebridge-ewelink#334]
@bwp91

RE: homebridge-ewelink v8.10.0

Working great!
Just wanted to say thank you Ben, for building what I perceive to be the best plugin available for Homebridge.

From the user experience all the way through the support provided for newly released devices, your plugin is: 

- Much better than Ring.
- Much better than Tuya.
- Much better than Wiz.

The other players need to step-it-up a notch or two!
There should be a Homebridge Plugin Hero Award!
![image](https://user-images.githubusercontent.com/68468472/148606154-c45fec5b-e8a2-4f06-89f0-d729727fcdf9.png)

**Comment by bwp91** [comment]
Hi @MoTechnicalities 

Thank you for this feedback, it's great to know the plugin is working well for you! Kudos to eWeLink too for their system which allows the plugin to work well, e.g. their persistent web socket connection which allows for real time updates, rather than the need for polling like some other plugins.

If you have the time, a review on the HOOBS website would be amazing, so long as you give it 5 stars ha!
https://plugins.hoobs.org/plugin/homebridge-ewelink

The hero picture is very cool, thank you!

**Comment by MoTechnicalities** [comment]
@bwp91

That works too! Go see it!

![image](https://user-images.githubusercontent.com/68468472/148652736-5b0a1295-e6c4-4f11-b083-e9b36e95bf67.png)

**Comment by bwp91** [comment]
That's super thanks a lot! Gonna close this, to keep track of the existing issues, seems a shame to close this but thank you!

**Comment by MoTechnicalities** [comment]
When the job is done, keep moving on!
