### ISSUE TITLE
Can I change the polling interval of Sonoff S31?

### ISSUE THREAD

**Issue by weilunw** [bwp91/homebridge-ewelink#353]
* **Please explain your feature request in a one or two sentences.**

The polling interval value was fixed after v6.4.0. Is it possible to provide this parameter for user?

* **Is your feature request related to a problem? Please describe.**

No

* **Any particular eWeLink devices that this relates to?**

S31

* **Anything else?**

**Comment by bwp91** [comment]
Hi @weilunw 

I hard-coded the polling interval since it has no effect on the incoming updates for power data.

The request that is sent to the device is to tell the device to send real-time data for the next two minutes. So the plugin sends this request every two minutes for always-enabled real time data.

It is not a polling request to obtain the power data every two minutes. It is a request to get the device to send updates for the next two minutes.

I hope this makes sense, and you can see how there is no need to change this value?
