### ISSUE TITLE
Self switched door Lock with no "operationTime" 

### ISSUE THREAD

**Issue by HElzomor** [bwp91/homebridge-ewelink#443]
* **Please explain your feature request in a one or two sentences.**
1-  I would like to have a door or a lock that is without "operationTime" and isn't based on inching, but based on switching.
-> I would like to open the door lock and close it both on command.
2- Is it possible to have a reversed indication? "on" means the lock is locked and "off" means the lock is unlocked.

* **Is your feature request related to a problem? Please describe.**
I have a switch connected to a magnetic lock locking the door. it has no operation time and it is normally open (the door is unlocked as long as the switch is "off")

* **Any particular eWeLink devices that this relates to?**
TX device

* **Anything else?**
Thanks a lot for your efforts! I have been using your plugin for almost 2 years now and it has evolved and helped wonderfully!! :)

**Comment by bwp91** [comment]
Hi @HZomor 

Please update to the beta version of the plugin, and also in your config set the operationTime of the lock to `0`.

You should find that you are then able to turn lock on and off based from the home app rather than anything timed.

Also let me know if I have this the wrong way (I mean in your case locked vs unlocked!)

Note I have not tested this so no promises this works first time!

**Comment by HElzomor** [comment]
Yes this is exactly what I meat. thanks a lot!
