### ISSUE TITLE
Device showing in home bridge but not in home app

### ISSUE THREAD

**Issue by sanskardhanda** [bwp91/homebridge-ewelink#96]
Hi I was able to connect app to homebridge but the device is not showing up in Apple Home app.

**Comment by bwp91** [comment]
Hi,

Obviously I want to try and help you but I also need you to help me with a bit more detail about your setup. Otherwise it's very difficult for me to pinpoint what's going wrong.

I assume you successfully installed this plugin into Homebridge and configured it with your ewelink details?

Which ewelink devices do you have?

Any errors in the Homebridge logs?

Thanks

**Comment by sanskardhanda** [comment]
Hi,
its pretty silly but I didn't refresh home-bridge earlier after restarting the device showed up. Thanks for the plugin.

**Comment by sanskardhanda** [comment]
Hi,
its pretty silly but I didn't refresh home-bridge earlier after restarting the device showed up. Thanks for the plugin.

**Comment by sanskardhanda** [comment]
Hi,
its pretty silly but I didn't refresh home-bridge earlier after restarting the device showed up. Thanks for the plugin.

**Comment by bwp91** [comment]
Great to here it’s working!
